language: objective-c

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email: false
  slack:
    rooms:
      secure: CZ3AxQUb2Vf1KpmxFDdA8zklQF/RjoR2M50trV6HG+WbMiYtA9V2oQQpsC4HpyOJrj/L88rBYYlfV60u0j5uDhI0UOogFR4XEObGPmnp5NxUOlpIcdZ+ElFa1MT+9pxk8BLhnSJ6dBfVeqis57Ex11yMHu2YSdBfmMtYEqTWHwT9544vRN3jRsXx2CmDBuNl9CW/WjITb4rZ6nefcPesG98ri/gu/9K6mFKOsknlQ/9bsfF9Km7y1UXmMlbQknJ0WMXgkNA4RiNl+1ryeTEms2qOgi6QwNvk9c/53CvA5FxB73KrEpOj/fCHfbuDBfsMwDLXAYzsCnj8ym2zYFfFPntq56uTfYceY3Eng7hIRlkXOWHSgpvO8uI9+vh6NroVbae5vAa6p2Ov0xYjh+XUdmcyOvNkw+DLpqaF2/hVnpfNqr6v5lVfaWFdoukp04/gtxcZ+ireXtKY9SbjDZhJGTX+TyqCxGHAiQPMIqEpfVHWNFEHYKwMf9cxNy6XN5yJg/ihfMX3my1xEj4mmbhkq3TKFQK+P55D7NIGcSfxu5OYc0uXrXhcv8KAYue3oLF/4cyEpCjzyfn1fYJqcUClvsyFFlKT5esPbACquo2fJT3P4AZjL/R3FmzEmMfgJGTNnbaFuguGL7qkEnK6ALLPdI9AkZ0uyJJ2QeOyzhP2s1I=
    on_start: never

# Should also affect tags
branches:
  except:
    # Skip building tagged releases
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
